// Generated by gencpp from file ros_essentials_cpp/Cart_relay.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_CART_RELAY_H
#define ROS_ESSENTIALS_CPP_MESSAGE_CART_RELAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct Cart_relay_
{
  typedef Cart_relay_<ContainerAllocator> Type;

  Cart_relay_()
    : relay1(false)
    , relay2(false)
    , relay3(false)
    , relay4(false)
    , relay5(false)
    , relay6(false)
    , relay7(false)
    , relay8(false)  {
    }
  Cart_relay_(const ContainerAllocator& _alloc)
    : relay1(false)
    , relay2(false)
    , relay3(false)
    , relay4(false)
    , relay5(false)
    , relay6(false)
    , relay7(false)
    , relay8(false)  {
  (void)_alloc;
    }



   typedef uint8_t _relay1_type;
  _relay1_type relay1;

   typedef uint8_t _relay2_type;
  _relay2_type relay2;

   typedef uint8_t _relay3_type;
  _relay3_type relay3;

   typedef uint8_t _relay4_type;
  _relay4_type relay4;

   typedef uint8_t _relay5_type;
  _relay5_type relay5;

   typedef uint8_t _relay6_type;
  _relay6_type relay6;

   typedef uint8_t _relay7_type;
  _relay7_type relay7;

   typedef uint8_t _relay8_type;
  _relay8_type relay8;





  typedef boost::shared_ptr< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> const> ConstPtr;

}; // struct Cart_relay_

typedef ::ros_essentials_cpp::Cart_relay_<std::allocator<void> > Cart_relay;

typedef boost::shared_ptr< ::ros_essentials_cpp::Cart_relay > Cart_relayPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::Cart_relay const> Cart_relayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/xy/catkin_ws/src/ros_essentials_cpp/msg', '/home/xy/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def73046ee79d2544a7074e6b203b9e0";
  }

  static const char* value(const ::ros_essentials_cpp::Cart_relay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdef73046ee79d254ULL;
  static const uint64_t static_value2 = 0x4a7074e6b203b9e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/Cart_relay";
  }

  static const char* value(const ::ros_essentials_cpp::Cart_relay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool relay1\n"
"bool relay2\n"
"bool relay3\n"
"bool relay4\n"
"bool relay5\n"
"bool relay6\n"
"bool relay7\n"
"bool relay8\n"
;
  }

  static const char* value(const ::ros_essentials_cpp::Cart_relay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.relay1);
      stream.next(m.relay2);
      stream.next(m.relay3);
      stream.next(m.relay4);
      stream.next(m.relay5);
      stream.next(m.relay6);
      stream.next(m.relay7);
      stream.next(m.relay8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cart_relay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::Cart_relay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::Cart_relay_<ContainerAllocator>& v)
  {
    s << indent << "relay1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay1);
    s << indent << "relay2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay2);
    s << indent << "relay3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay3);
    s << indent << "relay4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay4);
    s << indent << "relay5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay5);
    s << indent << "relay6: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay6);
    s << indent << "relay7: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay7);
    s << indent << "relay8: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_CART_RELAY_H
