// Generated by gencpp from file ros_essentials_cpp/CART_WETTING.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_CART_WETTING_H
#define ROS_ESSENTIALS_CPP_MESSAGE_CART_WETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct CART_WETTING_
{
  typedef CART_WETTING_<ContainerAllocator> Type;

  CART_WETTING_()
    : fan(false)
    , fanError(false)
    , wettingAgigator(0)
    , wettingAgigatorError(false)
    , waterRelay(false)
    , waterFlowRate(0)  {
    }
  CART_WETTING_(const ContainerAllocator& _alloc)
    : fan(false)
    , fanError(false)
    , wettingAgigator(0)
    , wettingAgigatorError(false)
    , waterRelay(false)
    , waterFlowRate(0)  {
  (void)_alloc;
    }



   typedef uint8_t _fan_type;
  _fan_type fan;

   typedef uint8_t _fanError_type;
  _fanError_type fanError;

   typedef int8_t _wettingAgigator_type;
  _wettingAgigator_type wettingAgigator;

   typedef uint8_t _wettingAgigatorError_type;
  _wettingAgigatorError_type wettingAgigatorError;

   typedef uint8_t _waterRelay_type;
  _waterRelay_type waterRelay;

   typedef int8_t _waterFlowRate_type;
  _waterFlowRate_type waterFlowRate;





  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> const> ConstPtr;

}; // struct CART_WETTING_

typedef ::ros_essentials_cpp::CART_WETTING_<std::allocator<void> > CART_WETTING;

typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WETTING > CART_WETTINGPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WETTING const> CART_WETTINGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/xy/catkin_ws/src/ros_essentials_cpp/msg', '/home/xy/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b94dfd08ede217b9cf320c1f63856e66";
  }

  static const char* value(const ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb94dfd08ede217b9ULL;
  static const uint64_t static_value2 = 0xcf320c1f63856e66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/CART_WETTING";
  }

  static const char* value(const ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool fan\n"
"bool fanError\n"
"int8 wettingAgigator\n"
"bool wettingAgigatorError\n"
"bool waterRelay\n"
"int8 waterFlowRate\n"
"\n"
;
  }

  static const char* value(const ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fan);
      stream.next(m.fanError);
      stream.next(m.wettingAgigator);
      stream.next(m.wettingAgigatorError);
      stream.next(m.waterRelay);
      stream.next(m.waterFlowRate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CART_WETTING_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::CART_WETTING_<ContainerAllocator>& v)
  {
    s << indent << "fan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fan);
    s << indent << "fanError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fanError);
    s << indent << "wettingAgigator: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wettingAgigator);
    s << indent << "wettingAgigatorError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wettingAgigatorError);
    s << indent << "waterRelay: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.waterRelay);
    s << indent << "waterFlowRate: ";
    Printer<int8_t>::stream(s, indent + "  ", v.waterFlowRate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_CART_WETTING_H
