// Generated by gencpp from file ros_essentials_cpp/CART_PUMP.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_CART_PUMP_H
#define ROS_ESSENTIALS_CPP_MESSAGE_CART_PUMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct CART_PUMP_
{
  typedef CART_PUMP_<ContainerAllocator> Type;

  CART_PUMP_()
    : freshConcreteLevel(0)
    , rotaryError(false)
    , upDownError(false)  {
    }
  CART_PUMP_(const ContainerAllocator& _alloc)
    : freshConcreteLevel(0)
    , rotaryError(false)
    , upDownError(false)  {
  (void)_alloc;
    }



   typedef int8_t _freshConcreteLevel_type;
  _freshConcreteLevel_type freshConcreteLevel;

   typedef uint8_t _rotaryError_type;
  _rotaryError_type rotaryError;

   typedef uint8_t _upDownError_type;
  _upDownError_type upDownError;





  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> const> ConstPtr;

}; // struct CART_PUMP_

typedef ::ros_essentials_cpp::CART_PUMP_<std::allocator<void> > CART_PUMP;

typedef boost::shared_ptr< ::ros_essentials_cpp::CART_PUMP > CART_PUMPPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::CART_PUMP const> CART_PUMPConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/xy/catkin_ws/src/ros_essentials_cpp/msg', '/home/xy/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce610b23c5e92af396a4558395a1815b";
  }

  static const char* value(const ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce610b23c5e92af3ULL;
  static const uint64_t static_value2 = 0x96a4558395a1815bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/CART_PUMP";
  }

  static const char* value(const ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 freshConcreteLevel\n"
"bool rotaryError\n"
"bool upDownError\n"
;
  }

  static const char* value(const ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.freshConcreteLevel);
      stream.next(m.rotaryError);
      stream.next(m.upDownError);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CART_PUMP_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::CART_PUMP_<ContainerAllocator>& v)
  {
    s << indent << "freshConcreteLevel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.freshConcreteLevel);
    s << indent << "rotaryError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rotaryError);
    s << indent << "upDownError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.upDownError);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_CART_PUMP_H
