// Generated by gencpp from file ros_essentials_cpp/CART_WAGON.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_CART_WAGON_H
#define ROS_ESSENTIALS_CPP_MESSAGE_CART_WAGON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct CART_WAGON_
{
  typedef CART_WAGON_<ContainerAllocator> Type;

  CART_WAGON_()
    : wagonDistance(0)
    , wagonInPosition(false)
    , wagonGateOpen(false)
    , wagonGateSpeed(0)
    , wagonGateMotorCurrent(0)
    , wagonGateClosed(false)  {
    }
  CART_WAGON_(const ContainerAllocator& _alloc)
    : wagonDistance(0)
    , wagonInPosition(false)
    , wagonGateOpen(false)
    , wagonGateSpeed(0)
    , wagonGateMotorCurrent(0)
    , wagonGateClosed(false)  {
  (void)_alloc;
    }



   typedef int8_t _wagonDistance_type;
  _wagonDistance_type wagonDistance;

   typedef uint8_t _wagonInPosition_type;
  _wagonInPosition_type wagonInPosition;

   typedef uint8_t _wagonGateOpen_type;
  _wagonGateOpen_type wagonGateOpen;

   typedef int8_t _wagonGateSpeed_type;
  _wagonGateSpeed_type wagonGateSpeed;

   typedef int8_t _wagonGateMotorCurrent_type;
  _wagonGateMotorCurrent_type wagonGateMotorCurrent;

   typedef uint8_t _wagonGateClosed_type;
  _wagonGateClosed_type wagonGateClosed;





  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> const> ConstPtr;

}; // struct CART_WAGON_

typedef ::ros_essentials_cpp::CART_WAGON_<std::allocator<void> > CART_WAGON;

typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WAGON > CART_WAGONPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::CART_WAGON const> CART_WAGONConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/xy/catkin_ws/src/ros_essentials_cpp/msg', '/home/xy/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2909bb836c26f898577403093e2bd371";
  }

  static const char* value(const ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2909bb836c26f898ULL;
  static const uint64_t static_value2 = 0x577403093e2bd371ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/CART_WAGON";
  }

  static const char* value(const ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 wagonDistance\n"
"bool wagonInPosition\n"
"bool wagonGateOpen\n"
"int8 wagonGateSpeed\n"
"int8 wagonGateMotorCurrent\n"
"bool wagonGateClosed\n"
;
  }

  static const char* value(const ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wagonDistance);
      stream.next(m.wagonInPosition);
      stream.next(m.wagonGateOpen);
      stream.next(m.wagonGateSpeed);
      stream.next(m.wagonGateMotorCurrent);
      stream.next(m.wagonGateClosed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CART_WAGON_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::CART_WAGON_<ContainerAllocator>& v)
  {
    s << indent << "wagonDistance: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wagonDistance);
    s << indent << "wagonInPosition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wagonInPosition);
    s << indent << "wagonGateOpen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wagonGateOpen);
    s << indent << "wagonGateSpeed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wagonGateSpeed);
    s << indent << "wagonGateMotorCurrent: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wagonGateMotorCurrent);
    s << indent << "wagonGateClosed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wagonGateClosed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_CART_WAGON_H
