(cl:in-package ros_essentials_cpp-msg)
(cl:export '(DELIVERYSWITCH-VAL
          DELIVERYSWITCH
          HOPPERSWITCH-VAL
          HOPPERSWITCH
          DOSERSWITCH-VAL
          DOSERSWITCH
          DOSERSPEED-VAL
          DOSERSPEED
          WETTINGSWITCH-VAL
          WETTINGSWITCH
          MIXERSWITCH-VAL
          MIXERSWITCH
          MIXERSPEED-VAL
          MIXERSPEED
          PUMPSWITCH-VAL
          PUMPSWITCH
          PUMPROTARYSPEED-VAL
          PUMPROTARYSPEED
          PUMPUPDOWNSPEED-VAL
          PUMPUPDOWNSPEED
          ESTOP-VAL
          ESTOP
          TOWER2CART-VAL
          TOWER2CART
          CART2TOWER-VAL
          CART2TOWER
          ROBOCLAW5PWM-VAL
          ROBOCLAW5PWM
          ROBOCLAW6PWM-VAL
          ROBOCLAW6PWM
))