(cl:in-package ros_essentials_cpp-msg)
(cl:export '(MOTOR1SPEED-VAL
          MOTOR1SPEED
          MOTOR2SPEED-VAL
          MOTOR2SPEED
          MOTOR3SPEED-VAL
          MOTOR3SPEED
          MOTOR4SPEED-VAL
          MOTOR4SPEED
          MOTOR1ERROR-VAL
          MOTOR1ERROR
          MOTOR2ERROR-VAL
          MOTOR2ERROR
          MOTOR3ERROR-VAL
          MOTOR3ERROR
          MOTOR4ERROR-VAL
          MOTOR4ERROR
          MOTOR1PWM-VAL
          MOTOR1PWM
          MOTOR2PWM-VAL
          MOTOR2PWM
          MOTOR3PWM-VAL
          MOTOR3PWM
          MOTOR4PWM-VAL
          MOTOR4PWM
          MOTOR1OVERCURRENT-VAL
          MOTOR1OVERCURRENT
          MOTOR2OVERCURRENT-VAL
          MOTOR2OVERCURRENT
          MOTOR3OVERCURRENT-VAL
          MOTOR3OVERCURRENT
          MOTOR4OVERCURRENT-VAL
          MOTOR4OVERCURRENT
          SENSOR1-VAL
          SENSOR1
          SENSOR2-VAL
          SENSOR2
          SENSOR3-VAL
          SENSOR3
          SENSOR4-VAL
          SENSOR4
          SENSOR5-VAL
          SENSOR5
          SENSOR6-VAL
          SENSOR6
          SENSOR7-VAL
          SENSOR7
          SENSOR8-VAL
          SENSOR8
          RELAY1-VAL
          RELAY1
          RELAY2-VAL
          RELAY2
          RELAY3-VAL
          RELAY3
          RELAY4-VAL
          RELAY4
          RELAY5-VAL
          RELAY5
          RELAY6-VAL
          RELAY6
          RELAY7-VAL
          RELAY7
          RELAY8-VAL
          RELAY8
          RELAY1ERROR-VAL
          RELAY1ERROR
          RELAY2ERROR-VAL
          RELAY2ERROR
          RELAY3ERROR-VAL
          RELAY3ERROR
          RELAY4ERROR-VAL
          RELAY4ERROR
          RELAY5ERROR-VAL
          RELAY5ERROR
          RELAY6ERROR-VAL
          RELAY6ERROR
          RELAY7ERROR-VAL
          RELAY7ERROR
          RELAY8ERROR-VAL
          RELAY8ERROR
          SERVOMOTOR1-VAL
          SERVOMOTOR1
          SERVOMOTOR2-VAL
          SERVOMOTOR2
          SERVOMOTOR3-VAL
          SERVOMOTOR3
          SERVOMOTOR4-VAL
          SERVOMOTOR4
          MIXINGCAMERA-VAL
          MIXINGCAMERA
))