(cl:in-package ros_essentials_cpp-msg)
(cl:export '(RELAY1ERROR-VAL
          RELAY1ERROR
          RELAY2ERROR-VAL
          RELAY2ERROR
          RELAY3ERROR-VAL
          RELAY3ERROR
          RELAY4ERROR-VAL
          RELAY4ERROR
          RELAY5ERROR-VAL
          RELAY5ERROR
          RELAY6ERROR-VAL
          RELAY6ERROR
          RELAY7ERROR-VAL
          RELAY7ERROR
          RELAY8ERROR-VAL
          RELAY8ERROR
          SENSOR1-VAL
          SENSOR1
          SENSOR2-VAL
          SENSOR2
          SENSOR3-VAL
          SENSOR3
          SENSOR4-VAL
          SENSOR4
          SENSOR5-VAL
          SENSOR5
          SENSOR6-VAL
          SENSOR6
          SENSOR7-VAL
          SENSOR7
          SENSOR8-VAL
          SENSOR8
          TEMPERATURE-VAL
          TEMPERATURE
          HUMIDITY-VAL
          HUMIDITY
          WINDSPEED-VAL
          WINDSPEED
          CONCRETETEMPERATURE-VAL
          CONCRETETEMPERATURE
          ACCELXNOZZLE-VAL
          ACCELXNOZZLE
          ACCELYNOZZLE-VAL
          ACCELYNOZZLE
          ACCELZNOZZLE-VAL
          ACCELZNOZZLE
          ACCELXCART-VAL
          ACCELXCART
          ACCELYCART-VAL
          ACCELYCART
          ACCELZCART-VAL
          ACCELZCART
))