(cl:in-package ros_essentials_cpp-msg)
(cl:export '(RELAY1-VAL
          RELAY1
          RELAY2-VAL
          RELAY2
          RELAY3-VAL
          RELAY3
          RELAY4-VAL
          RELAY4
          RELAY5-VAL
          RELAY5
          RELAY6-VAL
          RELAY6
          RELAY7-VAL
          RELAY7
          RELAY8-VAL
          RELAY8
          RCSERVO1-VAL
          RCSERVO1
          RCSERVO2-VAL
          RCSERVO2
          RCSERVO3-VAL
          RCSERVO3
          RCSERVO4-VAL
          RCSERVO4
          ROBOCLAW1ASPEED-VAL
          ROBOCLAW1ASPEED
          ROBOCLAW1A_P-VAL
          ROBOCLAW1A_P
          ROBOCLAW1A_I-VAL
          ROBOCLAW1A_I
          ROBOCLAW1A_D-VAL
          ROBOCLAW1A_D
          ROBOCLAW1A_QPPS-VAL
          ROBOCLAW1A_QPPS
          ROBOCLAW1BSPEED-VAL
          ROBOCLAW1BSPEED
          ROBOCLAW1B_P-VAL
          ROBOCLAW1B_P
          ROBOCLAW1B_I-VAL
          ROBOCLAW1B_I
          ROBOCLAW1B_D-VAL
          ROBOCLAW1B_D
          ROBOCLAW1B_QPPS-VAL
          ROBOCLAW1B_QPPS
          ROBOCLAW2ASPEED-VAL
          ROBOCLAW2ASPEED
          ROBOCLAW2A_P-VAL
          ROBOCLAW2A_P
          ROBOCLAW2A_I-VAL
          ROBOCLAW2A_I
          ROBOCLAW2A_D-VAL
          ROBOCLAW2A_D
          ROBOCLAW2A_QPPS-VAL
          ROBOCLAW2A_QPPS
          ROBOCLAW2BSPEED-VAL
          ROBOCLAW2BSPEED
          ROBOCLAW2B_P-VAL
          ROBOCLAW2B_P
          ROBOCLAW2B_I-VAL
          ROBOCLAW2B_I
          ROBOCLAW2B_D-VAL
          ROBOCLAW2B_D
          ROBOCLAW2B_QPPS-VAL
          ROBOCLAW2B_QPPS
          ROBOCLAW3A_PWM-VAL
          ROBOCLAW3A_PWM
          ROBOCLAW3B_PWM-VAL
          ROBOCLAW3B_PWM
          ROBOCLAW4A_PWM-VAL
          ROBOCLAW4A_PWM
          ROBOCLAW4B_PWM-VAL
          ROBOCLAW4B_PWM
))