# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_essentials_cpp/CART_MCU_O.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CART_MCU_O(genpy.Message):
  _md5sum = "44a60052a7c33b87fadfde548121603e"
  _type = "ros_essentials_cpp/CART_MCU_O"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool limitSwitch4
int8 ultraSonic4
"""
  __slots__ = ['limitSwitch4','ultraSonic4']
  _slot_types = ['bool','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       limitSwitch4,ultraSonic4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CART_MCU_O, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.limitSwitch4 is None:
        self.limitSwitch4 = False
      if self.ultraSonic4 is None:
        self.ultraSonic4 = 0
    else:
      self.limitSwitch4 = False
      self.ultraSonic4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bb().pack(_x.limitSwitch4, _x.ultraSonic4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.limitSwitch4, _x.ultraSonic4,) = _get_struct_Bb().unpack(str[start:end])
      self.limitSwitch4 = bool(self.limitSwitch4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bb().pack(_x.limitSwitch4, _x.ultraSonic4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.limitSwitch4, _x.ultraSonic4,) = _get_struct_Bb().unpack(str[start:end])
      self.limitSwitch4 = bool(self.limitSwitch4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bb = None
def _get_struct_Bb():
    global _struct_Bb
    if _struct_Bb is None:
        _struct_Bb = struct.Struct("<Bb")
    return _struct_Bb
