# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_essentials_cpp/Cart_wagon.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Cart_wagon(genpy.Message):
  _md5sum = "2909bb836c26f898577403093e2bd371"
  _type = "ros_essentials_cpp/Cart_wagon"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 wagonDistance
bool wagonInPosition
bool wagonGateOpen
int8 wagonGateSpeed
int8 wagonGateMotorCurrent
bool wagonGateClosed
"""
  __slots__ = ['wagonDistance','wagonInPosition','wagonGateOpen','wagonGateSpeed','wagonGateMotorCurrent','wagonGateClosed']
  _slot_types = ['int8','bool','bool','int8','int8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wagonDistance,wagonInPosition,wagonGateOpen,wagonGateSpeed,wagonGateMotorCurrent,wagonGateClosed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cart_wagon, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wagonDistance is None:
        self.wagonDistance = 0
      if self.wagonInPosition is None:
        self.wagonInPosition = False
      if self.wagonGateOpen is None:
        self.wagonGateOpen = False
      if self.wagonGateSpeed is None:
        self.wagonGateSpeed = 0
      if self.wagonGateMotorCurrent is None:
        self.wagonGateMotorCurrent = 0
      if self.wagonGateClosed is None:
        self.wagonGateClosed = False
    else:
      self.wagonDistance = 0
      self.wagonInPosition = False
      self.wagonGateOpen = False
      self.wagonGateSpeed = 0
      self.wagonGateMotorCurrent = 0
      self.wagonGateClosed = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2B2bB().pack(_x.wagonDistance, _x.wagonInPosition, _x.wagonGateOpen, _x.wagonGateSpeed, _x.wagonGateMotorCurrent, _x.wagonGateClosed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.wagonDistance, _x.wagonInPosition, _x.wagonGateOpen, _x.wagonGateSpeed, _x.wagonGateMotorCurrent, _x.wagonGateClosed,) = _get_struct_b2B2bB().unpack(str[start:end])
      self.wagonInPosition = bool(self.wagonInPosition)
      self.wagonGateOpen = bool(self.wagonGateOpen)
      self.wagonGateClosed = bool(self.wagonGateClosed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2B2bB().pack(_x.wagonDistance, _x.wagonInPosition, _x.wagonGateOpen, _x.wagonGateSpeed, _x.wagonGateMotorCurrent, _x.wagonGateClosed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.wagonDistance, _x.wagonInPosition, _x.wagonGateOpen, _x.wagonGateSpeed, _x.wagonGateMotorCurrent, _x.wagonGateClosed,) = _get_struct_b2B2bB().unpack(str[start:end])
      self.wagonInPosition = bool(self.wagonInPosition)
      self.wagonGateOpen = bool(self.wagonGateOpen)
      self.wagonGateClosed = bool(self.wagonGateClosed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2B2bB = None
def _get_struct_b2B2bB():
    global _struct_b2B2bB
    if _struct_b2B2bB is None:
        _struct_b2B2bB = struct.Struct("<b2B2bB")
    return _struct_b2B2bB
