# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_essentials_cpp/Cart_pump.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Cart_pump(genpy.Message):
  _md5sum = "ce610b23c5e92af396a4558395a1815b"
  _type = "ros_essentials_cpp/Cart_pump"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 freshConcreteLevel
bool rotaryError
bool upDownError
"""
  __slots__ = ['freshConcreteLevel','rotaryError','upDownError']
  _slot_types = ['int8','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       freshConcreteLevel,rotaryError,upDownError

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cart_pump, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.freshConcreteLevel is None:
        self.freshConcreteLevel = 0
      if self.rotaryError is None:
        self.rotaryError = False
      if self.upDownError is None:
        self.upDownError = False
    else:
      self.freshConcreteLevel = 0
      self.rotaryError = False
      self.upDownError = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.freshConcreteLevel, _x.rotaryError, _x.upDownError))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.freshConcreteLevel, _x.rotaryError, _x.upDownError,) = _get_struct_b2B().unpack(str[start:end])
      self.rotaryError = bool(self.rotaryError)
      self.upDownError = bool(self.upDownError)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.freshConcreteLevel, _x.rotaryError, _x.upDownError))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.freshConcreteLevel, _x.rotaryError, _x.upDownError,) = _get_struct_b2B().unpack(str[start:end])
      self.rotaryError = bool(self.rotaryError)
      self.upDownError = bool(self.upDownError)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2B = None
def _get_struct_b2B():
    global _struct_b2B
    if _struct_b2B is None:
        _struct_b2B = struct.Struct("<b2B")
    return _struct_b2B
