# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_essentials_cpp/test.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class test(genpy.Message):
  _md5sum = "b8d73f2e3c2cafcbf70065524e824454"
  _type = "ros_essentials_cpp/test"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 T1
float32 T2
float32 T3
int32 T4
"""
  __slots__ = ['T1','T2','T3','T4']
  _slot_types = ['int32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       T1,T2,T3,T4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(test, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.T1 is None:
        self.T1 = 0
      if self.T2 is None:
        self.T2 = 0.
      if self.T3 is None:
        self.T3 = 0.
      if self.T4 is None:
        self.T4 = 0
    else:
      self.T1 = 0
      self.T2 = 0.
      self.T3 = 0.
      self.T4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2fi().pack(_x.T1, _x.T2, _x.T3, _x.T4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.T1, _x.T2, _x.T3, _x.T4,) = _get_struct_i2fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2fi().pack(_x.T1, _x.T2, _x.T3, _x.T4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.T1, _x.T2, _x.T3, _x.T4,) = _get_struct_i2fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2fi = None
def _get_struct_i2fi():
    global _struct_i2fi
    if _struct_i2fi is None:
        _struct_i2fi = struct.Struct("<i2fi")
    return _struct_i2fi
