# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_essentials_cpp/TOWER_MCU_O.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TOWER_MCU_O(genpy.Message):
  _md5sum = "61126b5e7aa9f1b68cb1d9c626ee0799"
  _type = "ros_essentials_cpp/TOWER_MCU_O"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool limitSwitch2
bool limitSwitch3
int8 ultraSonic2
int8 ultraSonic3

"""
  __slots__ = ['limitSwitch2','limitSwitch3','ultraSonic2','ultraSonic3']
  _slot_types = ['bool','bool','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       limitSwitch2,limitSwitch3,ultraSonic2,ultraSonic3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TOWER_MCU_O, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.limitSwitch2 is None:
        self.limitSwitch2 = False
      if self.limitSwitch3 is None:
        self.limitSwitch3 = False
      if self.ultraSonic2 is None:
        self.ultraSonic2 = 0
      if self.ultraSonic3 is None:
        self.ultraSonic3 = 0
    else:
      self.limitSwitch2 = False
      self.limitSwitch3 = False
      self.ultraSonic2 = 0
      self.ultraSonic3 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2b().pack(_x.limitSwitch2, _x.limitSwitch3, _x.ultraSonic2, _x.ultraSonic3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.limitSwitch2, _x.limitSwitch3, _x.ultraSonic2, _x.ultraSonic3,) = _get_struct_2B2b().unpack(str[start:end])
      self.limitSwitch2 = bool(self.limitSwitch2)
      self.limitSwitch3 = bool(self.limitSwitch3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2b().pack(_x.limitSwitch2, _x.limitSwitch3, _x.ultraSonic2, _x.ultraSonic3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.limitSwitch2, _x.limitSwitch3, _x.ultraSonic2, _x.ultraSonic3,) = _get_struct_2B2b().unpack(str[start:end])
      self.limitSwitch2 = bool(self.limitSwitch2)
      self.limitSwitch3 = bool(self.limitSwitch3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2b = None
def _get_struct_2B2b():
    global _struct_2B2b
    if _struct_2B2b is None:
        _struct_2B2b = struct.Struct("<2B2b")
    return _struct_2B2b
